name: QKD Network CI

on:
  push:
    branches: [ main, QKD-network-build ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          cmake \
          ninja-build \
          libgtk-3-dev \
          libxml2-dev \
          libsqlite3-dev \
          libeigen3-dev \
          libgsl-dev \
          libboost-all-dev \
          python3-dev \
          python3-pip \
          clang-tidy

    - name: Install nlohmann-json
      run: |
        sudo apt-get install -y nlohmann-json3-dev

    - name: Configure build
      run: |
        cd ns-3-dev
        ./waf configure --enable-examples --enable-tests

    - name: Build with warnings as errors
      run: |
        cd ns-3-dev
        ./waf -j$(nproc) build

    - name: Run star topology smoke test
      run: |
        cd ns-3-dev
        timeout 30s ./waf --run "scratch/man_of13_qkd --topoJson=.ci/star.json --controllerType=static --simEnd=5 --qkdTestMode=baseline" > build/star_test.out 2>&1 || echo "Test completed"

    - name: Verify star test results
      run: |
        cd ns-3-dev
        if grep -q "Final key buffer: [1-9]" build/star_test.out; then
          echo "✓ Star test passed: Key material generated"
          grep "Final key buffer:" build/star_test.out
        else
          echo "✗ Star test failed: No key material found"
          cat build/star_test.out
          exit 1
        fi

    - name: Run ring topology regression test
      run: |
        cd ns-3-dev
        timeout 45s ./waf --run "scratch/man_of13_qkd --topoJson=.ci/ring.json --controllerType=rule --qkdTestMode=load --linkLoss=3.0" > build/ring_test.out 2>&1 || echo "Test completed"

    - name: Verify ring test performance
      run: |
        cd ns-3-dev
        # Check QBER is reasonable (< 3%)
        if grep -q "Session QBER: 0\.0[0-2]" build/ring_test.out; then
          echo "✓ Ring QBER test passed"
        else
          echo "✗ Ring QBER test failed"
          grep "Session QBER:" build/ring_test.out || echo "QBER not found"
          exit 1
        fi
        
        # Check key rate is reasonable (> 5 kbps)
        if grep -q "Average key rate: [56789][0-9][0-9][0-9]" build/ring_test.out; then
          echo "✓ Ring key rate test passed"
          grep "Average key rate:" build/ring_test.out
        elif grep -q "Average key rate: [1-9][0-9][0-9][0-9][0-9]" build/ring_test.out; then
          echo "✓ Ring key rate test passed (high rate)"
          grep "Average key rate:" build/ring_test.out  
        else
          echo "✗ Ring key rate test failed"
          grep "Average key rate:" build/ring_test.out || echo "Key rate not found"
          exit 1
        fi

    - name: Test command-line override functionality
      run: |
        cd ns-3-dev
        timeout 25s ./waf --run "scratch/man_of13_qkd --topoJson=.ci/star.json --controllerType=static --linkLoss=5.0 --simEnd=3" > build/override_test.out 2>&1 || echo "Test completed"
        
        # Verify override was applied
        if grep -q "Overriding core link loss to 5" build/override_test.out; then
          echo "✓ Command-line override test passed"
        else
          echo "✗ Command-line override test failed"
          cat build/override_test.out
          exit 1
        fi

    - name: Compile-time checks
      run: |
        cd ns-3-dev
        # Check for common warnings/errors with clang-tidy (subset)
        clang-tidy scratch/man_of13_qkd.cc -checks='-*,readability-*,performance-*' -- -I./build/include -I./src -std=c++17 > build/tidy.out 2>&1 || true
        
        # Don't fail on warnings for now, just report
        echo "Clang-tidy analysis:"
        head -20 build/tidy.out || echo "No clang-tidy output"

    - name: Upload test outputs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-outputs
        path: |
          ns-3-dev/build/star_test.out
          ns-3-dev/build/ring_test.out
          ns-3-dev/build/override_test.out
          ns-3-dev/build/tidy.out
